### ISSUE TITLE
Just upload and assign template to user, and nothing?

### ISSUE THREAD

**Issue by baoang** [cybersholt/VestaCP-Nginx-Force-SSL#1]
Hi, cybersholt,

Thank you for making a good template for VestaCP. I found the [thread via VestaCP's forum](https://forum.vestacp.com/viewtopic.php?f=11&t=14349#p66378) and followed your instruction. I uploaded the two template files to the dir at:
    /usr/local/vesta/data/templates/web/nginx/php-fpm
Then, in the controlling panel, I assigned the force-ssl template under **Web Template NGINX** section, and saved.

But I didn't see the desired results.

I typed http://example.com, the browser wouldn't bring me to https://example.com

also, http://www.example.com will not lead to https://example.com

Any hints on how to fig out what's the problem?

**Comment by cybersholt** [comment]
Hi @baoang,

No problem at all I plan on improving these and bringing a few more in here. 

For your VestaCP setup do you have apache installed or only nginx? 

`For Ubuntu try the command: apache2 -v

For CentOS: httpd -d `

If either of those give you a version number, you're vestacp has both apache & nginx, this is meant to work with nginx installs only. 

I made some adjustments this morning so this works better. Try these new files and then run `v-rebuild-web-domains` or via the gui, under user, check the user and from the select box choose `rebuild web`

And finally if you can let me know, your Host OS & Nginx version + anything else you think would be useful & I'll make a tested with list.

**Comment by baoang** [comment]
Hi, @cybersholt ,

I uploaded the your edited files to the server, pressed the `rebuild web` button, and went to cloudflare to turn off those CDN. 

It looks the redirect partially happened. If I typed in the URL bar *https://domain.com*, it would lead me to *https://www.domain.com*. Actually the reversed way I wanted(I prefer the no-www way).

For the http address, I am confused, because different browsers produced different results. Sometimes, they couldn't connect to the server, which I believe is due to the net connection problem. I will check this later on for the http to https forced redirection tomorrow and by mobile devices (so mobile will go from other ISP).

`httpd -d` didn't generate the version, and I am using CentOS. I didn't install Apache when installing VestaCP a few days ago. So all the modules remained the latest with the VestaCP official side.

And if my webpage is **default.html** rather than the commonly used **index.html**, should I make corresponding modifications from the wo tpl files? For example, should I make:

```
    index       index.php index.html index.htm;
```
to 

```
    index       default.html default.htm;
```

**Comment by baoang** [comment]
And here is a few couple things:

I checked the control panel, the **updates** menu on the top, and with the following info:
Vesta core package, Vesta-php and Vesta-nginx versions are all displayed as `0.9.8 (i686)  release 19`

I run only one domain on the server, and I don't have `www` CNAME record or **Aliases**(a column just above the **Web Template NGINX** section) I applied SSL from letsencrypt when I set the web directory to public_html, but after successfully obtained that I set the web directory to public_shtml and moved relevant web pages to the public_shtml dir.

**Comment by cybersholt** [comment]
Hi @baoang,

I'll make a non-www version for you as soon as I can and add it to this repo. I suggest adding the www alias just in case, that's probably why some browsers couldn't connect ( small note on windows for example you can type domain then hit CTRL+Enter & that auto fills the www & .com ). 

Regarding your default index file, you are correct.

Thanks for the info it really helps!

**Comment by cybersholt** [comment]
Hi @baoang,

Just created another version that should force https & no www, please give it a try and let me know how it works, I'm sort on time today to test this myself.

**Comment by baoang** [comment]
Hi, @cybersholt ,

Thank you for your help. I tried several hours ago, uploaded the new version to the php-fpm dir, and conducted *rebuild the web* operation. But due to (maybe) the local ISP's *DNS poisoninig*, which I am not sure because the browser displayed several times' `DNS PROBE FINISHED DOMAIN` alert, I couldn't connect to the domain.  I then reset my local machine's DNS, and about 10 minutes later, all was ok.

**Comment by cybersholt** [comment]
Hi @baoang ,

I'm glad to hear it's working, about the dns issue, I find using [google dns](https://developers.google.com/speed/public-dns/) and having the ability to [flush](https://developers.google.com/speed/public-dns/cache) it is really nice. Marking this as resolved, thanks again for the feedback!
