### ISSUE TITLE
ssl-no-www.tpl first line is github editor line counter

### ISSUE THREAD

**Issue by oxyplay** [cybersholt/VestaCP-Nginx-Force-SSL#2]
Thanks for templates! 
Noticed that ssl-no-www.tpl has " (30 sloc)  1.06 KB" string on first line and not working because of it.

**Comment by cybersholt** [comment]
@oxyplay just updated it, please re pull the code or update your template files manually. Please let me know if you encounter any issues at all.

**Comment by cybersholt** [comment]
Closed after fix
