### ISSUE TITLE
Is this working for the latest VestaCP?

### ISSUE THREAD

**Issue by cs16lover** [cybersholt/VestaCP-Nginx-Force-SSL#3]
Because I cannot find a screen to select ssl forced template?

**Comment by cybersholt** [comment]
@cs16lover yes it is and thank you so much for the fixes to the template files. I've also got a few more I'll get added in here.

**Comment by ZulqarnainKhaan** [comment]
the templates arent appearing in the VestaCP panel, can anyone help please?

**Comment by cybersholt** [comment]
@ZulqarnainKhaan follow the instructions and they will work.
